#define CLIENT(nick, user)							(nick + "!" + user + "@localhost")
#define PRIVMSG(client, target, message)			(":" + client + " PRIVMSG " + target + " :" + message + "\r\n")

#define RPL_JOIN(client, channel)					(":" + client + " JOIN " + channel + "\r\n")
#define RPL_PART(client, channel)					(":" + client + " PART " + channel + "\r\n")
#define RPL_PARTMESSAGE(client, channel, message)	(":" + client + " PART " + channel + " :" + message +"\r\n")
#define RPL_MODE(channel, mode)						(": MODE " + channel + ' ' + " :" + mode + "\r\n")
#define RPL_MODEARG(channel, mode, argument)		(": MODE " + channel + ' ' + mode + " :" + argument + "\r\n")
#define RPL_KICK(client, channel, target, reason)	(":" + client + " KICK " + channel + ' ' + target + ' ' + reason + "\r\n")
#define RPL_INVITERCVR(client, invitee, channel)	(":" + client + " INVITE " + invitee + ' ' + channel + "\r\n")
#define RPL_NICK(oldNick, newNick)					(":" + oldNick + " NICK " + newNick + "\r\n")
#define RPL_TOPIC(client, channel, topic)			(":" + client + " TOPIC " + channel + " :" + topic + "\r\n")
#define RPL_QUIT(client, message)					(":" + client + " QUIT :" + message + "\r\n")

#define RPL_WELCOME(nickname, client)				(": 001 " + nickname + " :Welcome to the IRC world, " + client + "\r\n")
#define RPL_UMODEIS(client, user_modes)				(": 221 " + client + ' ' + user_modes + "\r\n")
#define RPL_CHANNELMODEIS(client, channel, modes) 	(": 324 " + client + ' ' + channel + ' ' + modes + "\r\n")
#define RPL_CREATIONTIME(client, channel, \
	creationtime)									(": 329 " + client + ' ' + channel + ' ' + creationtime + "\r\n")
#define RPL_NOTOPIC(client, channel)				(": 331 " + client + ' ' + channel + " :No topic is set\r\n")
#define RPL_SEETOPIC(client, channel, topic)		(": 332 " + client + ' ' + channel + " :" + topic + "\r\n")
#define RPL_INVITESNDR(client, invitee, channel)	(": 341 " + client + ' ' + invitee + ' ' + channel + "\r\n")
#define RPL_NAMREPLY(client, channel, nicknames)	(": 353 " + client + " = " + channel + " :" + nicknames + "\r\n")
#define RPL_ENDOFNAMES(client, channel)				(": 366 " + client + ' ' + channel + " :End of /NAMES list.\r\n")

#define ERR_TOOMUCHPARAMS(client, cmd)				(client + ' ' + cmd + " :Too much parameters\r\n")
#define ERR_NOSUCHNICK(client, nickname) 			(": 401 " + client + ' ' + nickname + " :No such nick/channel\r\n")
#define ERR_NOSUCHCHANNEL(client, channel)			(": 403 " + client + ' ' + channel + " :No such channel\r\n")
#define ERR_CANNOTSENDTOCHAN(client, channel)		(": 404 " + client + ' ' + channel + " :Cannot send to channel\r\n")
#define ERR_NORECIPIENT(client, command)			(": 411 " + client + " :No recipient given (" + command + ")\r\n")
#define ERR_NOTEXTTOSEND(client)					(": 412 " + client + " :No text to send\r\n")
#define ERR_UNKNOWNCOMMAND(client, command)			(": 421 " + client + ' ' + command + " :Unknown command\r\n")
#define ERR_NONICKNAMEGIVEN(client, nick)			(": 431 " + client + ' ' + nick + " :No nickname given\r\n")
#define ERR_ERRONEUSNICKNAME(client, nickname)		(": 432 " + client + ' ' + nickname + " :Erroneus nickname\r\n")
#define ERR_NICKNAMEINUSE(nick)						(": 433 * " + nick + " :Nickname is already in use\r\n")
#define ERR_USERNOTINCHANNEL(client, nick, channel)	(": 441 " + client + ' ' + nick + ' ' + channel + " :They aren't on that channel\r\n")
#define ERR_NOTONCHANNEL(client, channel)			(": 442 " + client + ' ' + channel + " :You're not on that channel\r\n")
#define ERR_USERONCHANNEL(nick, channel)			(": 443 " + nick + ' ' + channel + " :is already on channel\r\n")
#define ERR_NOTREGISTERED()							(": 451 :You have not registered\r\n")
#define ERR_NEEDMOREPARAMS(client, cmd)				(": 461 " + client + ' ' + cmd + " :Not enough parameters\r\n")
#define ERR_ALREADYREGISTRED(client)				(": 462 " + client + " ::Unauthorized command (already registered)\r\n")
#define ERR_PASSWDMISMATCH(client)					(": 464 " + client + " :Password incorrect\r\n")
#define ERR_KEYSET(channel)							(": 467 " + channel + " :Channel key already set\r\n")
#define ERR_CHANNELISFULL(client, channel)			(": 471 " + client + ' ' + channel + " :Cannot join channel (+l)\r\n")
#define ERR_UNKNOWNMODE(client, mode)				(": 472 " + client + ' ' + mode + " :is not a recognised channel mode.\r\n")
#define ERR_INVITEONLYCHAN(client, channel)			(": 473 " + client + ' ' + channel + " :Cannot join channel (+i)\r\n")
#define ERR_BADCHANNELKEY(client, channel)			(": 475 " + client + ' ' + channel + " :Cannot join channel (+k)\r\n")
#define ERR_BADCHANMASK(channel)					(": 476 " + channel + " :Bad Channel Mask\r\n")
#define ERR_NOCHANMODES(channel)					(": 477 " + channel + " :Channel doesn't support modes\r\n")
#define ERR_CHANOPRIVSNEEDED(client, channel)		(": 482 " + client + ' ' + channel + " :You're not channel operator\r\n")
#define ERR_UMODEUNKNOWNFLAG(client)				(": 501 " + client + " :Unknown MODE flag\r\n")
#define ERR_USERSDONTMATCH(client)					(": 502 " + client + " :Cant change mode for other users\r\n")
#define ERR_INVALIDMODEPARAM(client, target, \
	mode_char, parameter, description)				(": 696 " + client + ' ' + target + ' ' + mode_char + ' ' + parameter + " :" + description + "\r\n")
